---

AllCops:
  NewCops: enable

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-factory_bot

Metrics/BlockLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
