---

name: Rubocop

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  rubocop:
    name: Rubocop Linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dependences
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libpq-dev postgresql-client build-essential libssl-dev

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3

      - name: Bundle Install
        run: bundle install

      - name: Rubocop Linter
        run: rubocop

      - name: Upload Rubocop Report
        uses: actions/upload-artifact@v2
        with:
          name: rubocop-report
          path: rubocop-output.json
